=== KManolov3/videoGameLibrary/videoGameCatalogue.dtd
<?xml version="1.0" encoding="utf-8"?>
    <!ELEMENT catalogue (genres, studios, video_games)>
	<!ELEMENT genres (genre+)>
	<!ELEMENT genre (genre_name)>
	<!ATTLIST genre genreID ID #REQUIRED>
    <!ATTLIST genre gameRef IDREFS #IMPLIED>
	<!ELEMENT genre_name (#PCDATA)>
	<!ELEMENT studios (studio+)>
	<!ELEMENT studio (studio_name, date_founded, studio_logo, headquarters, parent_company?)>
	<!ATTLIST studio studioID ID #REQUIRED>
	<!ATTLIST studio gameRef IDREFS #IMPLIED>
	<!ELEMENT studio_name (#PCDATA)>
	<!ELEMENT date_founded (#PCDATA)>
	<!ELEMENT studio_logo EMPTY>
	<!ATTLIST studio_logo href ENTITY #REQUIRED>
    <!ELEMENT headquarters (#PCDATA)>
    <!ELEMENT parent_company (#PCDATA)>
	<!ELEMENT video_games (video_game+)>
	<!ELEMENT video_game (video_game_name, game_logo, date_published, price, metacritic_score?, parental_guidance?, platforms?, description?, franchise_name?, game_modes?, 	additional_content?, awards?, gameplay_images?)>
	<!ATTLIST video_game gameID ID #REQUIRED>
	<!ATTLIST video_game genreRef IDREFS #IMPLIED>
	<!ATTLIST video_game studioRef IDREFS #IMPLIED>
    <!ELEMENT video_game_name (#PCDATA)>
    <!ELEMENT game_logo EMPTY>
	<!ATTLIST game_logo href ENTITY #REQUIRED>
    <!ELEMENT date_published (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ELEMENT metacritic_score (#PCDATA)>
    <!ELEMENT parental_guidance (#PCDATA)>
    <!ELEMENT platforms (platform+)>
    <!ELEMENT platform (#PCDATA)>
    <!ELEMENT description (#PCDATA)>
    <!ELEMENT franchise_name (#PCDATA)>
    <!ELEMENT game_modes (game_mode+)>
    <!ELEMENT game_mode (#PCDATA)>
    <!ELEMENT additional_content (content+)>
    <!ELEMENT content (name, type, date_published)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT type (#PCDATA)>
    <!ELEMENT date_content_published (#PCDATA)>
    <!ELEMENT awards (award+)>
    <!ELEMENT award (#PCDATA)>
    <!ELEMENT gameplay_images (gameplay_image_upper, gameplay_image_lower)>
    <!ELEMENT gameplay_image_upper EMPTY>
	<!ATTLIST gameplay_image_upper href ENTITY #REQUIRED>
	<!ELEMENT gameplay_image_lower EMPTY>
	<!ATTLIST gameplay_image_lower href ENTITY #REQUIRED>
	<!NOTATION jpg PUBLIC "jpg viewer">

=== KManolov3/videoGameLibrary/videoGameRepository.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="VideoGameCatalogue.xsl"?>

<!DOCTYPE game_catalogue SYSTEM "VideoGameCatalogue.dtd" [
	<!ENTITY bethesda_logo SYSTEM "images/studios/bethesda.jpg" NDATA jpg>
    <!ENTITY skyrim_logo SYSTEM "images/games/skyrim.jpg" NDATA jpg>
    <!ENTITY skyrim_gp1 SYSTEM "images/games/skyrim_gp1.jpg" NDATA jpg>
    <!ENTITY skyrim_gp2 SYSTEM "images/games/skyrim_gp2.jpg" NDATA jpg>
]>

<catalogue>


	<genres>
		<genre genreID = "rpg" gameRef="skyrim">
			<genre_name>Role-Playing Game</region_name>
		</genre>
		
	</genres>
	
	<studios>
		<studio studioID = "bethesda" gameRef="skyrim">
			<studio_name> Bethesda Game Studios </studio_name>
			<date_founded> 28.06.1986 </date_founded>
			<studio_logo href="bethesda_logo"/>
            <headquarters> Rockville, Maryland, United States </headquarters>
            <parent_company> Zenimax Studios </parent_company>
		</studio>
	</studios>
	
	<video_games>
		<video_game gameID="skyrim" genreRef="rpg" studioRef="bethesda">
			<video_game_name>The Elder Scrolls V: Skyrim</video_game_name>
            <game_logo href="skyrim_logo" />
			<date_published>11.11.2011</date_published>
			<price>40eur</price>
            <metacritic_score> 94% </metacritic_score>
            <parental_guidance> 12+ </parental_guidance>
			<platforms>
                <platform> Microsoft Windows </platform>
                <platform> Xbox 360 </platform>
                <platform> Xbox One </platform>
                <platform> Playstation 3 </platform>
                <platform> Playstation 4 </platform>
                <platform> Mintendo Switch </platform>
            </platforms>
			<description>
				The game's main story revolves around the player character's quest to defeat Alduin the World-Eater, a dragon who is prophesied to destroy the world. The game is set 200 years after the events of Oblivion and takes place in the fictional province of Skyrim. Over the course of the game, the player completes quests and develops the character by improving skills. The game continues the open-world tradition of its predecessors by allowing the player to travel anywhere in the game world at any time, and to ignore or postpone the main storyline indefinitely.
			</description>
            <franchise_name> The Elder Scrolls </franchise_name>
            <additional_content>
                <content>
                    <name> Dawnguard </name>
                    <type> DLC </type>
                    <date_published> 26.06.2012 </date_published>
                </content>
                <content>
                    <name> Hearthfire </name>
                    <type> DLC </type>
                    <date_published> 04.09.2012 </date_published>
                </content>
                <content>
                    <name> Dragonborn </name>
                    <type> DLC </type>
                    <date_published> 04.12.2012 </date_published>
                </content>
            </additional_content>
            <awards>
                <award> VGX Award for Best RPG 2011 </award>
                <award> AIAA Game of the Year 2011 </award>
                <award> GCA Best Console Game 2011 </award>
            </awards>
            <gameplay_images>
                <gameplay_image href="skyrim_gp1" />
                <gameplay_image href="skyrim_gp2" />
            </gameplay_images>	
		</video_game>
    </video_games>
    
</catalogue>
